using System.Collections.Generic;
using NUnit.Framework;
using Validate.Extensions;

namespace Validate.UnitTests
{
    [TestFixture]
    public class ValidatorTests_NullOrEmpty
    {
        [Test]
        public void ShouldPassForIsNullOrEmpty()
        {
            List<string> values = new List<string> { };
            var validator = values.Validate().IsNullOrEmpty(v => v, "Values canot be null or empty.");
            Assert.IsTrue(validator.IsValid);
        }

        [Test]
        public void ShouldFailForIsNullOrEmpty()
        {
            List<string> values = new List<string>{"One"};
            var validator = values.Validate().IsNullOrEmpty(v => v, "Values canot be null or empty");
            Assert.IsFalse(validator.IsValid);
        }

        [Test]
        public void ShouldBeAbleToVerifyAutoGeneratedValidationMessage1()
        {
            List<string> values = new List<string> { "One" };
            var validator = values.Validate().IsNullOrEmpty(v => v);
            Assert.That(validator.Errors[0].Message, Is.EqualTo("List`1[String].Value should be null or empty."));
        }

        [Test]
        public void ShouldBeAbleToVerifyAutoGeneratedValidationMessage2()
        {
            var person = new Person{Name = "Some Name", HomeAddress = new Address{AddressLine1 = "Line 1"}, EmailAddresses = new List<string>{"Email1", "Email2"}};
            var validator = person.Validate(new ValidationOptions { StopOnFirstError = false })
                            .IsNullOrEmpty(p => p.Name)
                            .IsNullOrEmpty(p => p.HomeAddress.AddressLine1)
                            .IsNullOrEmpty(p => p.EmailAddresses);
            Assert.That(validator.Errors[0].Message, Is.EqualTo("Person.Name should be null or empty."));
            Assert.That(validator.Errors[1].Message, Is.EqualTo("Address.AddressLine1 should be null or empty."));
            Assert.That(validator.Errors[2].Message, Is.EqualTo("Person.EmailAddresses should be null or empty."));
        }
    }
}