using System.Collections.Generic;
using NUnit.Framework;
using Validate.Extensions;

namespace Validate.UnitTests
{
    [TestFixture]
    public class ValidatorTests_NotNull
    {
        [Test]
        public void ShouldPassForIsNotNull()
        {
            List<string> values = new List<string>();
            var validator = values.Validate().IsNotNull(v => v, "Values cannot be null");
            Assert.IsTrue(validator.IsValid);
        }

        [Test]
        public void ShouldFailForIsNotNull()
        {
            List<string> values = null;
            var validator = values.Validate().IsNotNull(v => v, "Values cannot be null");
            Assert.IsFalse(validator.IsValid);
        }


        [Test]
        public void ShouldBeAbleToVerifyAutoGeneratedValidationMessage1()
        {
            List<string> values = null;
            var validator = values.Validate().IsNotNull(v => v);
            Assert.That(validator.Errors[0].Message, Is.EqualTo("List`1[String].{{ Target member could not be determined }} should not be null."));
        }

        [Test]
        public void ShouldBeAbleToVerifyAutoGeneratedValidationMessage2()
        {
            var person = new Person();
            var validator = person.Validate(new ValidationOptions { StopOnFirstError = false })
                            .IsNotNull(p => p.Name)
                            .IsNotNull(p => p.HomeAddress.AddressLine1);
            Assert.That(validator.Errors[0].Message, Is.EqualTo("Person.Name should not be null."));
            Assert.That(validator.Errors[1].Message, Is.EqualTo("Address.AddressLine1 should not be null."));
        }
    }
}