using NUnit.Framework;
using Validate.Extensions;

namespace Validate.UnitTests
{
    [TestFixture]
    public class ValidatorTests_OneOf
    {
        [Test]
        public void ShouldPassForOneOf()
        {
            var person = new Person { Name = "Person2" };

            var validator = person.Validate().IsOneOf(p => p, "Person is not one of people.", new Person { Name = "Person1" }, new Person { Name = "Person2" }, new Person { Name = "Person3" });
            Assert.IsTrue(validator.IsValid);
        }

        [Test]
        public void ShouldFailForOneOf()
        {
            var person = new Person { Name = "Person2" };

            var validator = person.Validate().IsOneOf(p => p, "Person is not one of people.", new Person { Name = "Person1" }, new Person { Name = "Person3" }, new Person { Name = "Person4" });
            Assert.IsFalse(validator.IsValid);
        }

        [Test]
        public void ShouldBeAbleToVerifyAutoGeneratedValidationMessage1()
        {
            var person = new Person { HomeAddress = new Address{Country = "USA"}};
            var validator = person.Validate()
                .IsOneOf(v => v.HomeAddress.Country, null, "UK", "Canada", "France");
            Assert.That(validator.Errors[0].Message, Is.EqualTo("Address.Country should be one of { UK | Canada | France }."));
        }
    }
}