using NUnit.Framework;
using Validate.Extensions;

namespace Validate.UnitTests
{
    [TestFixture]
    public class ValidatorTests_GreaterThan
    {
        [Test]
        public void ShouldPassForGreaterThan()
        {
            Assert.IsTrue(5.Validate().IsGreaterThan(i => i, 0, "Failed").IsValid);
        }

        [Test]
        public void ShouldFailForGreaterThan()
        {
            Assert.IsFalse(5.Validate().IsGreaterThan(i => i, 5, "Failed").IsValid);
            Assert.IsFalse(5.Validate().IsGreaterThan(i => i, 10, "Failed").IsValid);
        }

        [Test]
        public void ShouldBeAbleToVerifyAutoGeneratedValidationMessage1()
        {
            var person = new Person { Name = "Some Name", Age = 12, Goals = 22};
            var validator = person.Validate(new ValidationOptions { StopOnFirstError = false })
                .IsGreaterThan(v => v.Age, 18)
                .IsGreaterThan(v => v.Goals, 100);
            Assert.That(validator.Errors[0].Message, Is.EqualTo("Person.Age should be greater than 18."));
            Assert.That(validator.Errors[1].Message, Is.EqualTo("Person.Goals should be greater than 100."));
        }
    }
}