namespace Validate
{
    public class ValidationMessage
    {
        public string Message { get; private set; }
        private readonly bool _isAutoGenerated;

        public ValidationMessage(string message, bool isAutoGenerated = false)
        {
            Message = message;
            _isAutoGenerated = isAutoGenerated;
        }

        public override string ToString()
        {   
            return Message.Replace(TARGET_TYPE_NAME_PLACEHOLDER, "{0}").Replace(TARGET_MEMBER_NAME_PLACEHOLDER, "{1}");
        }

        public bool IsAutoGenerated
        {
            get { return _isAutoGenerated; }
        }

        private const string TARGET_TYPE_NAME_PLACEHOLDER = "{TargetType}";
        private const string TARGET_MEMBER_NAME_PLACEHOLDER = "{TargetMember}";
    }
}